# Generated by Django 4.2.7 on 2023-11-17 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='send_messages',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(help_text='Разрешается использовать только кириллицу, пробелы и дефис.', max_length=150, validators=[django.core.validators.RegexValidator(message='Введите допустимое слово. Должно содержать кириллицу, пробелы и дефисы', regex='^[а-яА-Я-]+\\s[а-яА-Я-]+\\s[а-яА-Я-]+$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Разрешается использовать только латиницу и дефис.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите допустимое слово. Должно содержать латиницу и дефисы.', regex='^[a-zA-Z-]+$')], verbose_name='Логин'),
        ),
    ]
