# Generated by Django 4.2.7 on 2023-11-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=150, verbose_name='Описание')),
                ('image_app', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('stas', models.CharField(choices=[('Н', 'Новая'), ('П', 'Принята в работу'), ('В', 'Выполнено')], default='Н', max_length=1, verbose_name='Статус заявки')),
                ('cat', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
    ]
